### ISSUE TITLE
Ability to change text color

### ISSUE THREAD

**Issue by codehippie1** [mymai91/react-native-toggle-element#10]
As per Issue#7, Adding activeColor and inActiveColor to thumbButton should handle text colors. Unfortunately - Though this works react native throws below error

Warning: Failed prop type: Invalid prop `thumbButton` key `activeColor` supplied to `ReactNativeToggleElement`.
Bad object: {
  "activeColor": "#ffffff",
  "inActiveColor": "#ffffff",
  "activeBackgroundColor": "#20639B",
  "inActiveBackgroundColor": "#20639B",
  "width": 84.88311688311688,
  "height": 37.13636363636364,
  "radius": 31.831168831168835
}
Valid keys: [
  "borderWidth",
  "width",
  "height",
  "radius",
  "activeBackgroundColor",
  "inActiveBackgroundColor"
]

**Comment by codehippie1** [comment]
Temporarily fixed the issue by adding the bolded lines of code on toggle.js
PS: I tried a pull request - For some reason, it is not letting me

ReactNativeToggleElement.propTypes = {
  onPress: PropTypes.func,
  value: PropTypes.bool.isRequired,
  disabled: PropTypes.bool,
  trackBar: PropTypes.exact({
    borderWidth: PropTypes.number,
    width: PropTypes.number,
    height: PropTypes.number,
    radius: PropTypes.number,
    activeBackgroundColor: PropTypes.string,
    inActiveBackgroundColor: PropTypes.string,
    borderActiveColor: PropTypes.string,
    borderInActiveColor: PropTypes.string,
  }),
  thumbButton: PropTypes.exact({
    borderWidth: PropTypes.number,
    width: PropTypes.number,
    height: PropTypes.number,
    radius: PropTypes.number,
    activeBackgroundColor: PropTypes.string,
    inActiveBackgroundColor: PropTypes.string,
    **inActiveColor: PropTypes.string,
    activeColor: PropTypes.string,**
  }),

**Comment by mymai91** [comment]
Hi @codehippie1, the issue has been fixed with version 2.0.0.
