### ISSUE TITLE
Please attach a method for Toggle Button - Unresolved

### ISSUE THREAD

**Issue by codehippie1** [mymai91/react-native-toggle-element#11]
See this definition from toggle.js. It is expecting onPress() not onToggle(). Should be an easy fix.

ReactNativeToggleElement.propTypes = {
  onPress: PropTypes.func,
  value: PropTypes.bool.isRequired,
  disabled: PropTypes.bool,
  trackBar: PropTypes.exact({
    borderWidth: PropTypes.number,
    width: PropTypes.number,
    height: PropTypes.number,
    radius: PropTypes.number,
    activeBackgroundColor: PropTypes.string,
    inActiveBackgroundColor: PropTypes.string,
    borderActiveColor: PropTypes.string,
    borderInActiveColor: PropTypes.string,
  }),

**Comment by mymai91** [comment]
@codehippie1 we are using onPress. You need to add a function for Toggle Button via onPress prop; otherwise, the toggle will raise the warning, so there is nothing to fix. 
I will close this issue.

**Comment by codehippie1** [comment]
@mymai91 The documentation mentiones about onToggle() prop. Yet toggle.js does not contain a definition for that. I temporarily avoided the warning by adding the below change to code on toggle.js

ReactNativeToggleElement.defaultProps = {
  **onToggle: () => console.warn('Please attach a method for Toggle Button'),
  onPress: () => {},**
  disabled: false,
  leftComponent: null,
  rightComponent: null,
  thumbActiveComponent: null,
  thumbInActiveComponent: null,
  trackBar: {
    borderWidth: SIZE_DEFAULT.borderWidth,
    width: SIZE_DEFAULT.trackBarWidth,
    height: SIZE_DEFAULT.trackBarHeight,
    radius: SIZE_DEFAULT.trackBarRadius,
    activeBackgroundColor: COLOR_DEFAULT.trackActiveBg,
    inActiveBackgroundColor: COLOR_DEFAULT.trackInActiveBg,
    borderActiveColor: COLOR_DEFAULT.borderColor,
    borderInActiveColor: COLOR_DEFAULT.borderColor,
  },
