### ISSUE TITLE
 Warning: Failed prop type: Invalid prop `leftComponent` supplied to `ReactNativeToggleElement`.

### ISSUE THREAD

**Issue by fahad39** [mymai91/react-native-toggle-element#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mymai91** [comment]
Hi @fahad39 , the issue has been fixed on version 2.0.0.
