### ISSUE TITLE
React-native 0.69 crash - TypeError: undefined Text.propTypes.style

### ISSUE THREAD

**Issue by LukasMod** [mymai91/react-native-toggle-element#16]
**Describe the bug**

After upgrading rn from 0.64.2 to 0.69.1 I got error before app starts:
`TypeError: undefined is not an object (evaluating ‘_reactNative.Text.propTypes.style’)`
With `grep -onr "Text.propTypes.style" .` I found out its this library cause crash. 

./node_modules/react-native-toggle-element/src/toggle.js:80:Text.propTypes.style
./node_modules/react-native-toggle-element/src/toggle.js:297:Text.propTypes.style

After removing it app works again.

**To Reproduce**
1. create app rn  >  0.69.0
2. add react-native-toggle-element 
3. build, start and see crash

**Expected behavior**
no crash

**Smartphone (please complete the following information):**
- web, ios, android
- react: "18.0.0",
- react-native: "0.69.1",
- react-native-toggle-element: "1.0.1"

**Comment by LukasMod** [comment]
I've created simple patch with `patch-package` just to fix crashing with 'any' propTypes, but it should definitely be updated correctly.

We cant now also use ViewPropTypes:
`ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types`

./patches/react-native-toggle-element+1.0.1.patch

```
diff --git a/node_modules/react-native-toggle-element/src/toggle.js b/node_modules/react-native-toggle-element/src/toggle.js
index cad66d9..e47e5ab 100644
--- a/node_modules/react-native-toggle-element/src/toggle.js
+++ b/node_modules/react-native-toggle-element/src/toggle.js
@@ -6,7 +6,6 @@ import {
   Text,
   TouchableOpacity,
   View,
-  ViewPropTypes,
 } from 'react-native';
 
 // PropsType
@@ -77,7 +76,7 @@ ThumbChildren.propTypes = {
   placement: PropTypes.oneOf(['left', 'right']).isRequired,
   children: PropTypes.element,
   disabled: PropTypes.bool,
-  disabledTitleStyle: Text.propTypes.style,
+  disabledTitleStyle: PropTypes.any,
 };
 
 ThumbChildren.defaultProps = {
@@ -291,11 +290,11 @@ ReactNativeToggleElement.propTypes = {
     PropTypes.string,
     PropTypes.element,
   ]),
-  containerStyle: ViewPropTypes.style,
-  trackBarStyle: ViewPropTypes.style,
-  disabledStyle: ViewPropTypes.style,
-  disabledTitleStyle: Text.propTypes.style,
-  thumbStyle: ViewPropTypes.style,
+  containerStyle: PropTypes.any,
+  trackBarStyle: PropTypes.any,
+  disabledStyle: PropTypes.any,
+  disabledTitleStyle: PropTypes.any,
+  thumbStyle: PropTypes.any,
   leftTitle: PropTypes.string,
   rightTitle: PropTypes.string,
   animationDuration: PropTypes.number
```

**Comment by vinhnglx** [comment]
@LukasMod thanks for sharing. However, the library creator is working on a new version with TS support. And it will fix quite a lof issues right now. It will be released within this month. 🙇

**Comment by mymai91** [comment]
Hi @LukasMod , @vinhnglx Thanks, the new version will be released soon.
