### ISSUE TITLE
Start with Neutral State

### ISSUE THREAD

**Issue by cip123** [mymai91/react-native-toggle-element#31]
**Is your feature request related to a problem? Please describe.**
I would like to know if the user selected a state (on or off) or when the user doesn't care about that field. 

**Describe the solution you'd like**
I would like to have a switch to start in a neutral (untouched) state

**Describe alternatives you've considered**
I considered using a button group, but it takes up too much space. 

**Additional context**
I found a (non-react-native) alternative here: https://codepen.io/Axiol/pen/mLKZyg

**Comment by mymai91** [comment]
Thank you, but I don't intend to support this feature at the moment.
