### ISSUE TITLE
Unable to make toggle state on(true) by default

### ISSUE THREAD

**Issue by asadqazi** [mymai91/react-native-toggle-element#4]
when keeping the state of toggle by default to true state, the toggle colors states updates but toggle thumb state do not get updated. 
For example: 
On left side its off and on right side its on 
and for default I want to keep it on. Then how will I move the thumb to right by default because currently by setting the `value={true}` it didn't work

**Comment by ChristianKuhn** [comment]
Same problem here. Also tried to manually call setState for the toggle value in the parent component's onComponentDidMount without success.

**Comment by jbernhardt23** [comment]
I had the same issue, I opened a PR to fix that https://github.com/mymai91/react-native-toggle-element/pull/2#issue-476496248

**Comment by asadqazi** [comment]
let see what happens. have you fixed it? @jbernhardt23

**Comment by mymai91** [comment]
@asadqazi @ChristianKuhn @jbernhardt23 Hi guys,

I have just published a new version (1.0.1) of the package.

Thank you @jbernhardt23  for the PR
