### ISSUE TITLE
Give us a way to change text colors

### ISSUE THREAD

**Issue by OmaKes** [mymai91/react-native-toggle-element#7]
Hello,

First of all thanks for the great work! the component is very usefull.

In my case, i have a toggle button, to let the user change the app language, it all work fine except the active language color is not white.

`import React, {useState} from 'react';
import Toggle from 'react-native-toggle-element';

const MyProjectSwitch = (props) => {

    const [initialValue, setInitialValue] = useState(props.initialValue);

    const onValueChanged = (newState) => {
        if(newState) {
            setInitialValue(true);
            props.ValueChangedHandler(props.rightTitle);
        } else {
            setInitialValue(false);
            props.ValueChangedHandler(props.leftTitle)
        }
    }

    return (
        <Toggle
            value={initialValue}
            onPress={(newState) => onValueChanged(newState)}
            leftTitle={props.leftTitle.toUpperCase()}
            rightTitle={props.rightTitle.toUpperCase()}
            trackBarStyle={{
                borderColor: 'white',
            }}
            trackBar={{
                activeBackgroundColor: 'transparent',
                inActiveBackgroundColor: 'transparent',
                borderActiveColor: 'white',
                borderInActiveColor: 'white',
                borderWidth: 1,
                width: 80,
                height: 25,
                radius: 25,
            }}
            thumbButton={{
                width: 40,
                height: 40,
                radius: 20,
                activeBackgroundColor: 'red',
                inActiveBackgroundColor: 'red',
            }}
        />
    );
}

export default MyProjectSwitch;
`

**Comment by mymai91** [comment]
@OmaKes you can try with
thumbButton={{
    activeColor: "red",
    inActiveColor: "yellow"
  }}
