### ISSUE TITLE
toggle position issue RTL application

### ISSUE THREAD

**Issue by NavidHosseini** [mymai91/react-native-toggle-element#9]
Hi, my project is  ًُRTL  and i use I18nManager.forceRTL(true) for it,.. when I press toggle, its location has a problem

![untitled](https://user-images.githubusercontent.com/56483402/116243297-0f55da00-a77c-11eb-9563-5d52a3f0a81b.gif)

![Screenshot_1619527536](https://user-images.githubusercontent.com/56483402/116243503-3e6c4b80-a77c-11eb-8030-9962fda73461.png)

Sorry my poor English..

**Comment by mymai91** [comment]
@NavidHosseini Sorry about it. For now, I don't have free time to fix it. Feel free to contribute the code to improve that one. I will merge if it passes the test case.
Thanks
